version: "3.9"

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8080:8000"
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - S3_ENDPOINT_URL=http://minio:9000
      - BUCKET=processed-images
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
