version: "3.9"

services:
  # app:
  #   build: .
  #   container_name: fastapi-app
  #   ports:
  #     - "8080:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - minio
  #   volumes:
  #       - ./ultralytics_config:/tmp/Ultralytics

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data

volumes:
  minio_data: